pasinter_api:
    resource: "@PasinterApiBundle/Controller/"
    type:     annotation
    prefix:   /

pasinter_account:
    resource: "@PasinterAccountBundle/Controller/"
    type:     annotation
    prefix:   /

pasinter_core:
    resource: "@PasinterCoreBundle/Controller/"
    type:     annotation
    prefix:   /

pasinter_backend:
    resource: "@PasinterBackendBundle/Controller/"
    type:     annotation
    prefix:   /

pasinter_frontend:
    resource: "@PasinterFrontendBundle/Controller/"
    type:     annotation
    prefix:   /


sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /resetting

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /register

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile
    
    
sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin