security:
    encoders:
        Pasinter\CoreBundle\Entity\User:
            algorithm: sha256
            encode_as_base64: false
            iterations: 1

        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    #user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: 32utjherg, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            login:
                pattern:    ^/login$
                security:      false
            logout:
                path:   _demo_logout
                target: _demo
            admin:
                pattern:    ^/admin
                anonymous:  ~
                http_basic:
                    realm:      "Admin"
                    provider:   in_memory
            account_area:
                pattern:    ^/account
                context:    site
                anonymous:  ~
                form_login:
                    login_path:             login
                    check_path:             /account/login_check
                    default_target_path:    /account
                    use_referer:            true
                logout:
                    path:       /account/logout
                    target:     homepage
                    #handlers:   [metacloud.connection_log_listener]

    access_control:
        - { path: ^/account/edit, roles: [ROLE_ORG_USER_ACTIVE, IS_AUTHENTICATED_FULLY] }
        - { path: ^/account, roles: [ROLE_ORG_USER] }
        - { path: ^/admin, roles: ROLE_SUPER_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
